### PR TITLE
Revise README  paras on bundle keywords, TAGs; define MAJOR, MINOR.

### PR DESCRIPTION
**Pull request by mvincerx**
Signed-off-by: michael vincerra <michael.vincerra@intel.com>

### CODE REVIEW

**Comment by mvincerx** [comment]
@phmccarty and @ahkok please review this PR per our talks. Thanks.

**Comment by mvincerx** [comment]
@ahkok.  Thanks for reviewing this. I'll follow up with you next week another script I'm working on to filter "Other" categories and reassign more accurate keywords.  After this PR is published, I'd also like to propose a brief training/email announcement to tie all this work together and build awareness of these requirements.

**Comment by mvincerx** [comment]
@phmccarty. Should be good to go now. Thanks for the review.

**Comment by phmccarty** [comment]
Looks good, +1

**Comment by phmccarty** [comment]
Fixed in f3b7a53bfd74ede53b208d2e6b2a9bb5851d2dd6 for release `31030`

**Pull request closed without merging**
