### PR TITLE
Add gnu-efi devpkg and fix sorting order in auto.devpkgs

### PR DESCRIPTION
**Pull request by gvancuts**

### CODE REVIEW

**Comment by ahkok** [comment]
+1 from me, @phmccarty to check and merge.

**Comment by gvancuts** [comment]
What would be the best way to achieve my objective here?
* Patch the `gnu-efi` code to generate a `gnu-efi.pc` file?
* Add `gnu-efi` to `packages.list` so as to create a pundle and also add it to `auto.devbundles`?
* ...?

**Comment by miguelinux** [comment]
> What would be the best way to achieve my objective here?
> * Patch the `gnu-efi` code to generate a `gnu-efi.pc` file?

I would said patch gnu-efi.

**Comment by gvancuts** [comment]
> I would said patch gnu-efi.

OK, let me see if I can take a stab at that.

Would it also make sense to file a feature request for our tooling to be able to generate `devpkg` even in the absence of such `pkgconfig` file? (It would make sense to me that a `devpkg` maps directly to what a `*-dev` RPM would provide)

**Comment by fenrus75** [comment]
rpms change name all the time

it's the .pc name that is the api

**Comment by gvancuts** [comment]
I have sent a patch to the mailing list to include a pkgconfig file for `gnu-efi` - see https://lists.clearlinux.org/pipermail/dev/2019-September/003497.html. It's the first time I go through this process so please let me know if I did anything incorrectly.

**Comment by bryteise** [comment]
Applied, thanks!

**Comment by bryteise** [comment]
Ah only applied the gnu-efi change, still needs to have the bundle work done after the pc file is in the distro.

**Pull request closed without merging**
